openapi: 3.0.0
info:
  title: Recommendation Service API
  description: API to get movie recommendations based on user history.
  version: 1.0.0
servers:
  - url: http://localhost:3004/api
    description: Local server for the recommendation-service
paths:
  /recommendations:
    get:
      summary: Get movie recommendations
      description: Returns a list of recommended movies based on the user's viewing history and preferences.
      operationId: getRecommendedMovies
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of recommended movies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Inception"
                    director:
                      type: string
                      example: "Christopher Nolan"
                    year:
                      type: integer
                      example: 2010
                    genre:
                      type: string
                      example: "Sci-Fi"
                    synopsis:
                      type: string
                      example: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO."
        '400':
          description: Unauthenticated user or user ID not provided
        '500':
          description: Error getting recommendations

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
