openapi: 3.0.0
info:
  title: Rating Service API
  description: API para calificar películas.
  version: 1.0.0
servers:
  - url: http://localhost:3003/api
    description: Servidor local para el rating-service
paths:
  /rate:
    post:
      summary: Calificar una película
      description: Permite a un usuario calificar una película proporcionando su ID y una puntuación.
      operationId: rateMovie
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - movieId
                - score
              properties:
                movieId:
                  type: integer
                  example: 1
                score:
                  type: integer
                  example: 5
      responses:
        '200':
          description: Película calificada con éxito
          content:
            application/json:
              schema:
                type: object
                properties:
                  movieId:
                    type: integer
                    example: 1
                  score:
                    type: integer
                    example: 5
                  userId:
                    type: integer
                    example: 1
                  createdAt:
                    type: string
                    format: date-time
                    example: "2023-04-01T12:34:56Z"
        '400':
          description: Datos inválidos o usuario no autorizado
        '401':
          description: Usuario no autenticado
        '404':
          description: Película no encontrada
        '500':
          description: Error interno del servidor

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
