openapi: 3.0.0
info:
  title: Rating Service API
  description: API for rating movies.
  version: 1.0.0
servers:
  - url: http://localhost:3003/api
    description: Local server for the rating service
paths:
  /rate:
    post:
      summary: Rate a movie
      description: Allows a user to rate a movie by providing its ID and a score.
      operationId: rateMovie
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - movieId
                - score
              properties:
                movieId:
                  type: integer
                  example: 1
                score:
                  type: integer
                  example: 5
      responses:
        '200':
          description: Film rated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  movieId:
                    type: integer
                    example: 1
                  score:
                    type: integer
                    example: 5
                  userId:
                    type: integer
                    example: 1
                  createdAt:
                    type: string
                    format: date-time
                    example: "2023-04-01T12:34:56Z"
        '400':
          description: Invalid data or unauthorized user
        '401':
          description: Unauthenticated user
        '404':
          description: Movie not found
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
