version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-rating
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_node
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  rating-service:
    build: .
    container_name: rating-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@db:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3003:3000"
    depends_on:
      - db

volumes:
  db_data:
