version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_node
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/proyecto_node
      JWT_SECRET: abc123

volumes:
  db_data:
