version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-shared
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_node
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3001:3000"
    depends_on:
      - mysql

  movie-service:
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    container_name: movie-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3002:3000"
    depends_on:
      - mysql

  rating-service:
    build:
      context: .
      dockerfile: rating-service/Dockerfile
    container_name: rating-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3003:3000"
    depends_on:
      - mysql

  recommendation-service:
    build:
      context: .
      dockerfile: recommendation-service/Dockerfile
    container_name: recommendation-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3004:3000"
    depends_on:
      - mysql

volumes:
  db_data:
