version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-movie
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_node
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  movie-service:
    build: .
    container_name: movie-service
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://root:root@db:3306/proyecto_node
      JWT_SECRET: abc123
    ports:
      - "3002:3000"
    depends_on:
      - db

volumes:
  db_data:
